#!/usr/bin/env bash
# This is a Bash script that configures an Ubuntu server with the below requirements.
echo "127.0.0.2 localhost" > newhosts
tail +2 /etc/hosts >> newhosts
echo "8.8.8.8 facebook.com" >> newhosts
cp /etc/hosts actualhosts
sudo cp newhosts /etc/hosts
